name = "cloudflare"
main ="_worker.js"
compatibility_date = "2026-08-09"
vars = "true"
defaultProxyIP = "cdn-b100.xn--b6gac.eu.org"

githubProxyURL = "https://raw.githubusercontent.com/proxzero/galaxy-subdomain/refs/heads/main/PROXYIP.txt"

 dohURLs = [
    "https://cloudflare-dns.com/dns-query",
    "https://dns.google/dns-query"
]
