name = ""
main ="_worker.js"

defaultProxyIP = "cdn-b100.xn--b6gac.eu.org";

githubProxyURL = "https://raw.githubusercontent.com/proxzero/galaxy-subdomain/refs/heads/main/PROXYIP.txt"

 dohURLs = [
    "https://cloudflare-dns.com/dns-query",
    "https://dns.google/dns-query"
]
